config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :reservations, only: [:index, :show]
    resources :users, only: [:index, :destroy]
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: 'users#index'
  resources :users, only: [:index, :show]
  resources :reservations, only: [:index, :new, :create, :show, :destroy] do
    collection do
      post 'confirm'
    end
    resources :certificates, only: [:show, :new, :create, :edit, :update]
  end
  resources :cars, only: [:new, :create, :edit, :update, :destroy]
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  require 'active_support/all'
  include ReservationsHelper

  belongs_to :user
  has_one    :certificate, dependent: :destroy

  with_options presence: true do
    validates :park_num
    validates :start_datetime
    validates :end_datetime
  end

  validate :s_time_open_check
  validate :s_time_deadline_check
  validate :e_time_open_check
  validate :e_time_deadline_check
  validate :check_overbooking
  validate :count_reserv_below_three

  private

  def s_time_open_check
    s_time_open = (DateTime.current + 1.hour).beginning_of_hour
    errors.add(:start_datetime, 'は現在の日時より後を選択してください。') if start_datetime.present? && start_datetime < s_time_open
  end

  def s_time_deadline_check
    s_time_deadline = DateTime.current.next_month.end_of_month
    errors.add(:start_datetime, 'がまだ予約できない期間になっています。') if start_datetime.present? && start_datetime > s_time_deadline
  end

  def e_time_open_check
    if start_datetime.present? && end_datetime.present? && end_datetime <= start_datetime
      errors.add(:end_datetime, 'は開始日時より後を選択してください。')
    end
  end

  def e_time_deadline_check
    e_time_deadline = start_datetime + 24.hours if start_datetime.present?
    if end_datetime.present? && e_time_deadline.present? && end_datetime >= e_time_deadline
      errors.add(:end_datetime, 'は開始日時の24時間以内を選択してください。')
    end
  end

  def check_overbooking
    if start_datetime.present? && end_datetime.present?
      list = get_group_list(start_datetime, park_num)
      check_hour = start_datetime
      flag = 0
      while check_hour < end_datetime
        list.each do |reserv|
          result = check_hour.between?(reserv[:start_datetime], reserv[:end_datetime])
          flag += 1 if result == true
        end
        check_hour += 1.hour
      end
      if flag.positive?
        errors.add(:base, :invalid, message: '指定の日時には既に他の予約が入っています。変更してください。')
        false
      else
        true
      end
    end
  end

  def count_reserv_below_three
    valid_reserv = Reservation.where('end_datetime > ?', DateTime.current).where('user_id = ?', user_id)
    errors.add(:base, :invalid, message: '既に3件の予約があります。一度にとれる予約は3つまでです。') if valid_reserv.length >= 3
  end
end

app/controllers/admin/reservations_controller.rb
class Admin::ReservationsController < ApplicationController
  before_action :are_you_admin?

  def index
    @reservations = Reservation.order("created_at DESC")
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  private

  def are_you_admin?
    # ログイン中かつadminがtrueでなければrootへ
    redirect_to root_path if authenticate_user! && !current_user.admin
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  require 'active_support/all'
  include ReservationsHelper
  before_action :set_reserv, only: [:confirm, :create]

  def index
  end

  def show
    @dtime = params[:id].in_time_zone
    @reservation = Reservation.new
    @reservations = get_all_list(@dtime)
  end

  def new
    @reservation = Reservation.new
    @reservation[:park_num] = params[:park_num]
    @reservation[:start_datetime] = params[:start_datetime]
    @reservation[:end_datetime] = @reservation[:start_datetime]
  end

  def confirm
    render :new if @reservation.invalid?
  end

  def create
    render :new if params[:back] || !@reservation.save
  end

  def destroy
    reservation = Reservation.find(params[:id])
    reservation.destroy
    redirect_to root_path
  end

  private

  def reserv_params
    params.require(:reservation).permit(:start_datetime, :end_datetime, :park_num).merge(user_id: current_user.id)
  end

  def set_reserv
    @reservation = Reservation.new(reserv_params)
  end
end

app/helpers/admin/reservations_helper.rb
module Admin::ReservationsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper

  # 抜き出した予約データを駐車場番号ごとに配列に並べる
  def get_all_list(date)
    lists = []
    (1..4).each do |num|
      list = get_group_list(date, num)
      lists << list
    end
    lists
  end

  # 指定した駐車場番号で開始時間と終了時間のどちらかが指定日に入っている予約を抜き出す
  def get_group_list(date, num)
    Reservation.where(park_num: num).where(
      start_datetime: date.beginning_of_day..date.end_of_day
    ).or(
      Reservation.where(park_num: num).where(
        end_datetime: date.beginning_of_day..date.end_of_day
      )
    )
  end

  def check_reservation(lists, date, hour)
    unless lists.empty?                       # リストが空でなければ処理を実行
      lists.each do |reserv|
        result = (date + hour.hour).between?( # チェックするセルの時間が予約と重なるか
                  reserv[:start_datetime], 
                  reserv[:end_datetime]
                  )
        return result if result == true       # 重なっていればtrueを返す
      end
    end
    return false                              # リストが空か重なりがなければfalse
  end
end

app/views/admin/reservations/index.html.erb
<div class="main main-widen">
  <%= tag.h2 "予約一覧", class: "page-title" %>

  <div class="all-list-table-container js-scrollable sortable-table">
    <table class="all-list-table">
      <tr>
        <%= tag.th "ID", class: "sortable-header" %>
        <%= tag.th "駐車場", class: "sortable-header" %>
        <%= tag.th "開始日時", class: "sortable-header" %>
        <%= tag.th "終了日時", class: "sortable-header" %>
        <%= tag.th "部屋番号", class: "sortable-header" %>
        <%= tag.th "予約者", class: "sortable-header" %>
        <%= tag.th "予約作成日時", class: "sortable-header" %>
        <%= tag.th "許可証申請", class: "sortable-header" %>
      </tr>
      <% @reservations.each do |reservation| %>
        <tr>
          <%= tag.td reservation.id, class: "center-text" %>
          <%= tag.td "#{reservation.park_num}番", class: "center-text" %>
          <%= tag.td l reservation.start_datetime %>
          <%= tag.td l reservation.end_datetime %>
          <%= tag.td "#{reservation.user.building_num.name} #{reservation.user.room_num.name}" %>
          <%= tag.td "#{reservation.user.last_name} #{reservation.user.first_name}" %>
          <%= tag.td l reservation.created_at %>
          <td class="center-text">
            <% if reservation.certificate.present? %>
              <%= link_to '提出済', admin_reservation_path(reservation.id), class: "colored-btn narrow-btn" %>
            <% else %>
              <%= tag.p '未提出' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/reservations/show.html.erb
<div class="main">
  <h2 class="page-title">
    利用許可証申請内容
  </h2>
  <div class="user-info-content">
    <div class="admin-reserv-wrapper mobile-blocky">
      <%= tag.div "予約情報", class: "caption" %>
      <table class="info-table mobile-blocky">
        <tr class="odd-row">
          <%= tag.th "予約ID" %>
          <%= tag.td @reservation.id %>
        </tr>
        <tr>
          <%= tag.th "駐車場番号" %>
          <%= tag.td "#{@reservation.park_num}番" %>
        </tr>
        <tr class="odd-row">
          <%= tag.th "予約日時" %>
          <%= tag.td "#{l @reservation.start_datetime} 〜 #{l @reservation.end_datetime}" %>
        </tr>
        <tr>
          <%= tag.th "使用車輌（車種）" %>
          <%= tag.td "#{@reservation.certificate.car_model}" %>
        </tr>
        <tr class="odd-row">
          <%= tag.th "車両登録番号"%>
          <%= tag.td "#{@reservation.certificate.license_num}" %>
        </tr>
        <tr>
          <%= tag.th "使用者氏名(運転者)" %>
          <%= tag.td "#{@reservation.certificate.drivers_name}" %>
        </tr>
        <tr class="odd-row">
          <%= tag.th "訪問先" %>
          <%= tag.td "#{@reservation.certificate.building_num.name} 
                      #{@reservation.certificate.room_num.name} 
                      #{@reservation.certificate.destination}様方"
          %>
        </tr>
        <tr>
          <%= tag.th "予約作成日時" %>
          <%= tag.td "#{l @reservation.created_at}" %>
        </tr>
        <tr class="odd-row">
          <%= tag.th "申請内容最終更新日時" %>
          <%= tag.td "#{l @reservation.certificate.updated_at}" %>
        </tr>
      </table>
      <%= tag.div "利用者情報", class: "caption" %>
      <table class="info-table mobile-blocky">
        <tr class="odd-row">
          <%= tag.th "部屋番号" %>
          <%= tag.td "#{@reservation.user.building_num.name} #{@reservation.user.room_num.name}" %>
        </tr>
        <tr>
          <%= tag.th "登録者氏名" %>
          <%= tag.td "#{@reservation.user.last_name} #{@reservation.user.first_name}" %>
        </tr>
        <tr class="odd-row">
          <%= tag.th "メールアドレス" %>
          <%= tag.td "#{@reservation.user.email}" %>
        </tr>
      </table>
    </div>
  </div>
  <%= render partial: "shared/backward_btn", locals: { linked_path: admin_reservations_path, page: "予約一覧" } %>
</div>