config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :reservations, only: [:index, :show]
    resources :users, only: [:index, :destroy]
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: 'users#index'
  resources :users, only: [:index, :show]
  resources :reservations, only: [:index, :new, :create, :show, :destroy] do
    collection do
      post 'confirm'
    end
    resources :certificates, only: [:show, :new, :create, :edit, :update]
  end
  resources :cars, only: [:new, :create, :edit, :update, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reservations, dependent: :destroy
  has_many :cars, dependent: :destroy
  belongs_to :building_num
  belongs_to :room_num

  with_options presence: true do
    validates :building_num_id, numericality: { other_than: 0, message: "を選択してください" }
    validates :room_num_id, uniqueness: { scope: :building_num_id },  numericality: { other_than: 0, message: "を選択してください" }
  end

  NAME_REGEX = /\A[ぁ-んァ-ヶ一-龥々ー]+\z/.freeze
  NAME_REGEX_MSG = 'は全角文字（漢字・ひらがな・カタカナ）を使用してください。再入力をお願いします。'.freeze
  with_options presence: true, format: { with: NAME_REGEX, message: NAME_REGEX_MSG } do
    validates :last_name
    validates :first_name
  end

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  PASSWORD_REGEX_MSG = 'には英字と数字をそれぞれ1文字以上含めるようにしてください。再入力をお願いします。'.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: PASSWORD_REGEX_MSG, if: :password_required?

  # 更新時に現在のpasswordを不要にする
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    # passwordとpassword_confirmationが空の場合、passwordの更新はされずに情報を更新する
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.where.not(admin: true).order(:building_num_id, :room_num_id)
  end

  def destroy
    user = User.find(params[:id])
    if user.destroy
      redirect_to admin_users_path
    else
      render :index
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_update_path_for(_resource)
    user_path(current_user)
  end

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @reservations = Reservation.where('end_datetime > ?', DateTime.current).where('user_id = ?', current_user.id).order("start_datetime ASC")
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="main">
  <div class="message">
    <%= current_user.last_name %>さん、こんにちは！<br>
    <% if @reservations.present? %>
      現在の予約状況は以下の通りです。<br>
      終了日時を過ぎたものは自動で非表示になります。
    <% else %>
      現在、予約はありません。
    <% end %>
  </div>
  
  <% @reservations.each.with_index(1) do |reservation, index| %>
    <div class="reserv-info-content">
      <div class="info-title">
        予約<%= index %>
      </div>
      <div class="reserv-content-wrapper">
        <div class="left-content">
          <%= render partial: "shared/reserv_info_table", locals: { reservation: reservation } %>
        </div>

        <div class="btn-content">
          <%# 「許可証の申請ボタン」、申請済みなら「許可証表示ボタン」と「申請内容の変更ボタン」 %>
          <% if reservation.certificate.present? %> 
            <%= render partial: "shared/generate_pdf_btn", locals: { 
              reserv_id: reservation.id, 
              certif_id: reservation.certificate.id 
              }
            %>
            <%= render partial: "shared/edit_certificate_btn", locals: { 
              reserv_id: reservation.id, 
              certif_id: reservation.certificate.id 
              }
            %>
          <% else %>
            <%= render partial: "shared/new_certificate_btn", locals: { reserv_id: reservation.id } %>
          <% end %>
          <%# 削除ボタン %>
          <% confirm_msg = "削除後は元に戻せません。\nこの予約を削除しますか？\nよろしければ【OK】ボタンを押してください。" %>
          <%= render partial: "shared/delete_btn", locals: {
                      linked_path: reservation_path(reservation.id), 
                      confirm_msg: confirm_msg
          } %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="main">
  <h2 class="page-title">
    利用者情報
  </h2>
  <div class="user-info-content">
    <div class="info-title">
      利用者情報
    </div>
    <div class="user-content-wrapper mobile-blocky">
      <div class="left-content">
        <table class="user-info mobile-blocky">
          <tr>
            <%= tag.th "部屋番号" %>
            <%= tag.td "#{@user.building_num.name} #{@user.room_num.name}" %>
          </tr>
          <tr>
            <%= tag.th "登録者氏名" %>
            <%= tag.td "#{@user.last_name} #{@user.first_name}" %>
          </tr>
          <tr>
            <%= tag.th "メールアドレス" %>
            <%= tag.td "#{@user.email}" %>
          </tr>
        </table>
      </div>

      <div class="btn-content">
        <%= render partial: "shared/edit_btn", locals: { linked_path: edit_user_registration_path } %>
        <% confirm_msg = "#{@user.last_name}さん！\n利用者登録を削除すると現在の予約もすべて削除されます。\n本当に削除しますか？\nよろしければ【OK】ボタンを押してください。" %>
        <%= render partial: "shared/delete_btn", locals: {
                            linked_path: user_registration_path, 
                            confirm_msg: confirm_msg
        } %>
      </div>
    </div>
  </div>

  <div class="mycar-title-wrapper mobile-blocky">
    <%= tag.h2 "車両情報", class: "mycar-title" %>
    <div class="rectangular btn short mycar-registration">
      <span class="material-icons btn-icon">
        add_box
      </span>
      <div class="btn-text">
        <%= link_to "新規登録", new_car_path %>
      </div>
    </div>
  </div>

  <% if @user.cars.present? %>
    <% (@user.cars).each do |car| %>
      <div class="mycar-content">
        <div class="info-title">
          <%= tag.div car[:nickname] %>
        </div>
        <div class="mycar-content-wrapper mobile-blocky">
          <div class="left-content">
            <table class="mycar-info mobile-blocky">
              <tr>
                <%= tag.th "使用車輌（車種）" %>
                <%= tag.td car[:model] %>
              </tr>
              <tr>
                <%= tag.th "車両登録番号"%>
                <%= tag.td car[:license_num] %>
              </tr>
              <tr>
                <%= tag.th "使用者氏名" %>
                <%= tag.td car[:drivers_name] %>
              </tr>
            </table>
          </div>

          <div class="btn-content">
            <%= render partial: "shared/edit_btn", locals: { linked_path: edit_car_path(car.id) } %>
            <% confirm_msg = "登録車両『#{car.nickname}』を削除しますか？\nよろしければ【OK】ボタンを押してください。" %>
            <%= render partial: "shared/delete_btn", locals: { linked_path: car_path(car.id), confirm_msg: confirm_msg } %>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="mycar-content">
      現在登録された車両はありません。<br>
      よく利用する車を登録しておくと許可証の申請時に自動入力が利用できます。
    </div>
  <% end %>
  <%= render partial: "shared/backward_btn", locals: { linked_path: root_path, page: "トップページ" } %>
</div>