config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :reservations, only: [:index, :show]
    resources :users, only: [:index, :destroy]
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: 'users#index'
  resources :users, only: [:index, :show]
  resources :reservations, only: [:index, :new, :create, :show, :destroy] do
    collection do
      post 'confirm'
    end
    resources :certificates, only: [:show, :new, :create, :edit, :update]
  end
  resources :cars, only: [:new, :create, :edit, :update, :destroy]
end

app/views/shared/_backward_btn.html.erb
  <div class="backward-wrapper">
    <%= link_to "#{page}へ戻る", linked_path, class: "colored-btn btn" %>
  </div>

app/views/shared/_car_form.html.erb
  <%= form_with model: car, local: true, class: "car-form" do |f| %>
  <div class="car-form-contents">
    <%= render "shared/error_messages", resource: f.object %>
    <table class="car-form-table mobile-blocky">
      <tr class="form-content">
        <%= tag.th (f.label :nickname, "識別用ニックネーム", class: 'required') %>
        <%= tag.td (f.text_field :nickname, placeholder: "例)通勤用など", autofocus: true) %>
      </tr>
      <tr class="form-content">
        <%= tag.th (f.label :model, "使用車両（車種）", class: 'required') %>
        <%= tag.td (f.text_field :model) %>
      </tr>
      <tr class='form-content'>
        <%= tag.th (f.label :license_num, "車両登録番号", class: 'required') %>
        <%= tag.td (f.text_field :license_num) %>
      </tr>
      <tr class='form-content'>
        <%= tag.th (f.label :drivers_name, "使用者氏名", class: 'required') %>
        <%= tag.td (f.text_field :drivers_name) %>
      </tr>
    </table>
      <%= f.submit '登録', class: "colored-btn btn" %>
    <% end %>
  </div>

app/views/shared/_certif_form.html.erb
<%= form_with model: [reservation, certificate], class: "certificate-form", local: true do |f| %>
  <%= render "shared/error_messages", resource: f.object %>

  <%# 既に決まっている情報 %>
  <div class="reserv-info-wrapper">
    <%= render partial: "shared/reserv_info_table", locals: { reservation: reservation } %>
  </div>
  <%# 新たに必要な情報 %>
  <div class="form-contents-wrapper">
    <div class="left-container">
      <%= f.label :dest_id, "訪問先の入力" %><br>
      <% if current_user.admin %>
        <%= f.select :dest_id, options_for_select({"管理事務所" => 1, "[新規で入力]" => 2}), include_blank: "選択してください" %>
      <% else %>
        <%= f.select :dest_id, options_for_select({"自宅" => 1, "[新規で入力]" => 2}), include_blank: "選択してください" %>
      <% end %>
    </div>
    <div class="right-container">
      <%= f.label :building_num_id, "部屋番号", class: "required" %><br>
      <div class="build-num">
        <% if current_user.admin %>
          <div>
            <%= f.collection_select(:building_num_id, BuildingNum.all, :id, :name, {}, selected: 0) %>
          </div>
          <div>
            <%= f.collection_select(:room_num_id, RoomNum.all, :id, :name, {}) %>
          </div>
        <% else %>
          <div>
            <%= f.collection_select(:building_num_id, BuildingNum.where.not(id: 9), :id, :name, {}, selected: 0) %>
          </div>
          <div>
            <%= f.collection_select(:room_num_id, RoomNum.where.not(id: 41), :id, :name, {}) %>
          </div>
        <% end %>
      </div>
      <%= f.label :destination, "訪問先", class: "required" %><br>
      <%= f.text_field :destination, placeholder: "例)✕✕", class: "destination" %>様方
    </div>
  </div>

  <div class="form-contents-wrapper">
    <div class="left-container">
      <%= f.label :car_id, "使用車輌の入力" %><br>
      <%= f.collection_select :car_id, cars, :id, :nickname, include_blank: "選択してください" %>
    </div>
    <div class="right-container">
      <div class="">
        <%= f.label :car_model, "使用車両(車種)", class: "required" %><br>
        <%= f.text_field :car_model, placeholder: "例)HONDA プリウスなど" %>
      </div>
      <div class="">
        <%= f.label :license_num, "車両登録番号", class: "required" %><br>
        <%= f.text_field :license_num, placeholder: "例)習志野●● あ 00-00など" %>
      </div>
      <div class="">
        <%= f.label :drivers_name, "使用者氏名(運転手)", class: "required" %><br>
        <%= f.text_field :drivers_name %>
      </div>
    </div>
  </div>
  <%= f.submit "申請", class: 'white-btn btn' %>
<% end %>

app/views/shared/_delete_btn.html.erb
  <div class="rectangular btn short alt-color">
    <span class="material-icons btn-icon">
      delete
    </span>
    <div class="btn-text">
      <%= link_to "削除する", linked_path, method: :delete, data: { confirm: confirm_msg } %>
    </div>
  </div>

app/views/shared/_edit_btn.html.erb
<div class="rectangular btn short">
  <span class="material-icons btn-icon">
    edit
  </span>
  <div class="btn-text">
    <%= link_to "編集する", linked_path %>
  </div>
</div>

app/views/shared/_edit_certificate_btn.html.erb
<div class="rectangular btn long">
  <span class="material-icons btn-icon">
    edit_note
  </span>
  <div class="btn-text">
    <%= link_to "許可証申請の変更", edit_reservation_certificate_path(reserv_id, certif_id) %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="copyright">
    copyright©ABCマンション管理組合
  </div>
</footer>

app/views/shared/_generate_pdf_btn.html.erb
<div class="rectangular btn long">
  <span class="material-icons btn-icon">
    print
  </span>
  <div class="btn-text">
    <%= link_to "許可証を表示・印刷", reservation_certificate_path(reserv_id, certif_id) %>
  </div>
</div>

app/views/shared/_header.html.erb
<header>
    <div class="logo">
      <h1><%= link_to "トットコ！", root_path %></h1>
      <p>ABCマンション(仮)来客用駐車場予約アプリ</p>
    </div>
</header>

<nav>
  <ul class="nav-bar">
    <% if user_signed_in? %>
      <li class="nav-item"><%= link_to "トップページ", root_path %></li>
      <%# adminだけ表示されるボタン %>
      <% if current_user.admin? %>
        <li class="nav-item"><%= link_to "予約一覧", admin_reservations_path %></li>
        <li class="nav-item"><%= link_to "利用者一覧", admin_users_path %></li>
      <% end %>
      <li class="nav-item"><%= link_to "予約表", reservations_path %></li>
      <li class="nav-item"><%= link_to "利用者情報", user_path(current_user.id) %></li>
      <li class="nav-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
    <% end %>
  </ul>
</nav>

app/views/shared/_header_admin.html.erb
<header class="admin">
    <div class="logo admin">
      <h1><%= link_to "トットコ！", root_path %></h1>
      <p>ABCマンション(仮)来客用駐車場予約アプリ</p>
    </div>
</header>

<nav class="admin">
  <ul class="nav-bar">
    <% if user_signed_in? %>
      <li class="nav-item"><%= link_to "トップページ", root_path %></li>
      <li class="nav-item"><%= link_to "予約一覧", admin_reservations_path %></li>
      <li class="nav-item"><%= link_to "利用者一覧", admin_users_path %></li>
      <li class="nav-item"><%= link_to "予約表", reservations_path %></li>
      <li class="nav-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
    <% end %>
  </ul>
</nav>

app/views/shared/_new_certificate_btn.html.erb
<div class="rectangular btn long">
  <span class="material-icons-outlined btn-icon" area-hidden="true" focusable="false">
    article
  </span>
  <div class="btn-text">
    <%= link_to "利用許可証の申請", new_reservation_certificate_path(reserv_id) %>
  </div>
</div>

app/views/shared/_new_ticket_btn.html.erb
<div class="square btn">
  <span class="material-icons btn-icon">
    picture_as_pdf
  </span>
  <div class="btn-text">
    <%= link_to "許可証", new_reservation_ticket_path(reserv_id) %>
  </div>
</div>

app/views/shared/_reserv_info_table.html.erb
<table class="reserv-info mobile-blocky">
  <tr>
    <%= tag.th "開始日時" %>
    <%= tag.td (l reservation.start_datetime) %>
  </tr>
  <tr>
    <%= tag.th "終了日時" %>
    <%= tag.td (l reservation.end_datetime) %>
  </tr>
  <tr>
    <%= tag.th "駐車場番号" %>
    <%= tag.td ("#{reservation.park_num}番") %>
  </tr>
</table>