config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :reservations, only: [:index, :show]
    resources :users, only: [:index, :destroy]
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: 'users#index'
  resources :users, only: [:index, :show]
  resources :reservations, only: [:index, :new, :create, :show, :destroy] do
    collection do
      post 'confirm'
    end
    resources :certificates, only: [:show, :new, :create, :edit, :update]
  end
  resources :cars, only: [:new, :create, :edit, :update, :destroy]
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  require 'active_support/all'
  include ReservationsHelper

  belongs_to :user
  has_one    :certificate, dependent: :destroy

  with_options presence: true do
    validates :park_num
    validates :start_datetime
    validates :end_datetime
  end

  validate :s_time_open_check
  validate :s_time_deadline_check
  validate :e_time_open_check
  validate :e_time_deadline_check
  validate :check_overbooking
  validate :count_reserv_below_three

  private

  def s_time_open_check
    s_time_open = (DateTime.current + 1.hour).beginning_of_hour
    errors.add(:start_datetime, 'は現在の日時より後を選択してください。') if start_datetime.present? && start_datetime < s_time_open
  end

  def s_time_deadline_check
    s_time_deadline = DateTime.current.next_month.end_of_month
    errors.add(:start_datetime, 'がまだ予約できない期間になっています。') if start_datetime.present? && start_datetime > s_time_deadline
  end

  def e_time_open_check
    if start_datetime.present? && end_datetime.present? && end_datetime <= start_datetime
      errors.add(:end_datetime, 'は開始日時より後を選択してください。')
    end
  end

  def e_time_deadline_check
    e_time_deadline = start_datetime + 24.hours if start_datetime.present?
    if end_datetime.present? && e_time_deadline.present? && end_datetime >= e_time_deadline
      errors.add(:end_datetime, 'は開始日時の24時間以内を選択してください。')
    end
  end

  def check_overbooking
    if start_datetime.present? && end_datetime.present?
      list = get_group_list(start_datetime, park_num)
      check_hour = start_datetime
      flag = 0
      while check_hour < end_datetime
        list.each do |reserv|
          result = check_hour.between?(reserv[:start_datetime], reserv[:end_datetime])
          flag += 1 if result == true
        end
        check_hour += 1.hour
      end
      if flag.positive?
        errors.add(:base, :invalid, message: '指定の日時には既に他の予約が入っています。変更してください。')
        false
      else
        true
      end
    end
  end

  def count_reserv_below_three
    valid_reserv = Reservation.where('end_datetime > ?', DateTime.current).where('user_id = ?', user_id)
    errors.add(:base, :invalid, message: '既に3件の予約があります。一度にとれる予約は3つまでです。') if valid_reserv.length >= 3
  end
end

app/controllers/admin/reservations_controller.rb
class Admin::ReservationsController < ApplicationController
  before_action :are_you_admin?

  def index
    @reservations = Reservation.order("created_at DESC")
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  private

  def are_you_admin?
    # ログイン中かつadminがtrueでなければrootへ
    redirect_to root_path if authenticate_user! && !current_user.admin
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  require 'active_support/all'
  include ReservationsHelper
  before_action :set_reserv, only: [:confirm, :create]

  def index
  end

  def show
    @dtime = params[:id].in_time_zone
    @reservation = Reservation.new
    @reservations = get_all_list(@dtime)
  end

  def new
    @reservation = Reservation.new
    @reservation[:park_num] = params[:park_num]
    @reservation[:start_datetime] = params[:start_datetime]
    @reservation[:end_datetime] = @reservation[:start_datetime]
  end

  def confirm
    render :new if @reservation.invalid?
  end

  def create
    render :new if params[:back] || !@reservation.save
  end

  def destroy
    reservation = Reservation.find(params[:id])
    reservation.destroy
    redirect_to root_path
  end

  private

  def reserv_params
    params.require(:reservation).permit(:start_datetime, :end_datetime, :park_num).merge(user_id: current_user.id)
  end

  def set_reserv
    @reservation = Reservation.new(reserv_params)
  end
end

app/helpers/admin/reservations_helper.rb
module Admin::ReservationsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper

  # 抜き出した予約データを駐車場番号ごとに配列に並べる
  def get_all_list(date)
    lists = []
    (1..4).each do |num|
      list = get_group_list(date, num)
      lists << list
    end
    lists
  end

  # 指定した駐車場番号で開始時間と終了時間のどちらかが指定日に入っている予約を抜き出す
  def get_group_list(date, num)
    Reservation.where(park_num: num).where(
      start_datetime: date.beginning_of_day..date.end_of_day
    ).or(
      Reservation.where(park_num: num).where(
        end_datetime: date.beginning_of_day..date.end_of_day
      )
    )
  end

  def check_reservation(lists, date, hour)
    unless lists.empty?                       # リストが空でなければ処理を実行
      lists.each do |reserv|
        result = (date + hour.hour).between?( # チェックするセルの時間が予約と重なるか
                  reserv[:start_datetime], 
                  reserv[:end_datetime]
                  )
        return result if result == true       # 重なっていればtrueを返す
      end
    end
    return false                              # リストが空か重なりがなければfalse
  end
end

app/views/reservations/confirm.html.erb
<div class="main">
  <h2 class="page-title">内容の確認</h2>
  <p class="message">
    内容に間違いがなければ、確定ボタンを押してください。
  </p>

  <div class="reserv-form">
    <div class="reserv-info-wrapper">
      <%= render partial: "shared/reserv_info_table", locals: { reservation: @reservation } %>
    </div>
    <%= form_with model: @reservation, local: true, class: "confirm-form" do |f| %>
      <%= f.hidden_field :start_datetime %>
      <%= f.hidden_field :end_datetime %>
      <%= f.hidden_field :park_num %>
      <%= f.submit '戻る', name: :back, class: "colored-btn btn" %>
      <%= f.submit '確定', class: "white-btn btn" %>
    <% end %>
  </div>
</div>

app/views/reservations/create.html.erb
<div class="main">
  <%= tag.h2 "予約完了", class: "page-title" %>
  <p class="message">
    予約が完了しました。<br>
    このまま利用許可証の申請に進む場合は「利用許可証の申請」ボタンを押してください。<br>
    利用許可証の申請はトップページからいつでもおこなえます。<br>
    利用開始日時までに申請をし、許可証を印刷してご利用ください。
  </p>
  <div class="reserv-finished-page__btn-wrapper mobile-blocky">
    <%= render partial: "shared/new_certificate_btn", locals: { reserv_id: @reservation.id } %>
    <div class="rectangular btn long">
      <span class="material-icons btn-icon" area-hidden="true" focusable="false">
        arrow_circle_up
      </span>
      <div class="btn-text">
        <%= link_to "トップページへ戻る", root_path %>
      </div>
    </div>
  </div>
</div>

app/views/reservations/index.html.erb
<div class="main">
  <%= tag.h2 "予約表", class: "page-title" %>
  <p class="message">
    確認したい日付をクリックまたはタップしてください。<br>
    翌月末まで予約することができます。
  </p>
  <%= month_calendar do |date| %>
    <%= link_to "#{date.day}", reservation_path(date) %>
  <% end %>
  <%= render partial: "shared/backward_btn", locals: { linked_path: root_path, page: "トップページ" } %>
</div>

app/views/reservations/new.html.erb
<div class="main">
  <h2 class="page-title">予約日時の入力</h2>
  <p class="message">
    項目を入力して予約ボタンを押してください。
  </p>
  <%= form_with model: @reservation, url: confirm_reservations_path, class: "reserv-form", local: true do |f| %>
    <%= render "shared/error_messages", resource: f.object %>
    
    <div class="form-content">
      <%= f.label :start_datetime, '開始日時', class: 'required' %><br/>
      <%= f.datetime_select :start_datetime, discard_minute: true %>:00から
    </div>
    <div class="form-content">
      <%= f.label :end_datetime, '終了日時', class: 'required'%><br/>
      <%= f.datetime_select :end_datetime, discard_minute: true %>:59まで
    </div>
    <div class='form-content'>
      <div class='required'>駐車場番号</div>
      <% (1..4).each do |num| %>
        <div class="radio-btn">
        <%= f.radio_button :park_num, num %>
        <%= f.label ":park_num_#{num}", "#{num}番" %>
        </div>
      <% end %>
    </div>
    <%= f.submit '確認画面へ', class: 'colored-btn btn', id:'reserv_submit' %>
  <% end %>
  <%= render partial: "shared/backward_btn", locals: { linked_path: reservation_path(@reservation[:start_datetime].beginning_of_day), page: "時間選択ページ" } %>
</div>

app/views/reservations/show.html.erb
<div class="main">
  <p class="message">
    予約開始時間の枠をクリックまたはタップしてください。<br/>
    1回の予約で確保できるのは最大24時間です。
  </p>

  <%# ナビゲータ %>
  <div class="timetable-heading">
    <div class="prev-day">
      <%= link_to "<< 前日を表示", reservation_path(@dtime.yesterday) %>
    </div>
    <div class="timetable-title">
      <%= tag.span l @dtime, format: :year %><br>
      <%= l @dtime, format: :date %>
    </div>
    <div class="next-day">
      <%= link_to "翌日を表示 >>", reservation_path(@dtime.tomorrow) %>
    </div>
  </div>

  <%# テーブルの描画 %>
  <div class="timetable-container js-scrollable">
    <table class="timetable">
      <thead>
        <tr>
          <%= tag.th class: "hours-cell" %>
          <% 24.times do |hour| %>
            <%= tag.th(class: "hours-cell") {tag.div "#{hour}時", class: "hour-label"} %>
          <% end %>
          <%= tag.th(class: "hours-cell") {tag.div 0, class: "hour-label"} %>
        </tr>
      </thead>

      <tbody>
        <% (1..4).each do |num| %> 
          <tr>
            <th class="p_num-wrapper"> 
              <%= tag.div(num, class: "p_num_label p_num_#{num}") %>
            </th>
            <% 24.times do |hour| %>
              <td class="cell">
                <% if check_reservation(@reservations[num - 1], @dtime, hour) %>
                  <%= tag.div "✕", class: "reserved_bar p_num_#{num}" %>
                <% else %>
                  <%= button_to "○", new_reservation_path, method: :get, class: "time-submit", params: {park_num: num, start_datetime: (@dtime + hour.hour)} %>
                <% end %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= render partial: "shared/backward_btn", locals: { linked_path: reservations_path, page: "カレンダーページ" } %>
</div>